apiVersion: apps/v1
kind: Deployment
metadata:
  name: amd-test
  labels:
    app: amd-test
spec:
  replicas: 7
  selector:
    matchLabels:
      app: amd-test
  template:
    metadata:
      labels:
        app: amd-test
    spec:
      containers:
      - name: amd
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: 500m
      nodeSelector:
        kubernetes.io/arch: amd64

